namespace: cryoem-logbook-dev

bases:
- ../../base/

resources:
- ns.yaml
- database-storage.yaml
- ingress.yaml

patchesStrategicMerge:
- storage-patches.yaml
- nodeSelector-patches.yaml

secretGenerator:
- name: mongodb
  literals:
  - username=admin
  - password=somepassword
- name: explgbk-writer
  literals:
  - username=writer
  - password=somepassword
- name: explgbk-reader
  literals:
  - username=reader
  - password=somepassword
- name: auth-secrets
  files:
  - ./cert.crt
  - ./intermediates.cer
  - ./cert.key
  - ./keytab_webauth
  - ./backend.htpasswd

images:
- name: slaclab/explgbk-docker
  newTag: '20200121.0'
